---
title: "Assignment_1"
author: "Kaustav"
date: "2025-09-05"
output: html_document
---

```{r}
#Load dataset from web
# Load libraries
library(tidyverse)

# Load dataset using full path
ev_data <- read.csv("C:/Users/kaust/Downloads/Assignment_1_data/Electric_Vehicle_Population_Data.csv")

# Preview data
head(ev_data)
```

```{r}
#Quantitative Variables
summary(select(ev_data, Model.Year, Electric.Range, Base.MSRP))
```

```{r}
#Categorical Variables
table(ev_data$Make)[1:10]   # First 10 car manufacturers
table(ev_data$County)[1:10] # First 10 counties
```

```{r}
#Variable Transformation (to handle skewness in price).
ev_data <- ev_data %>%
  mutate(Log_MSRP = log(Base.MSRP + 1)) # add 1 to avoid log(0)

summary(ev_data$Log_MSRP)
```


```{r}
#Histogram of Electric Range (for quantitative plot)
hist(ev_data$Electric.Range, 
     main = "Distribution of Electric Vehicle Ranges", 
     xlab = "Electric Range (miles)", 
     col = "purple", border = "black")
```



```{r}
#Scatterplot: MSRP vs Electric Range
plot(ev_data$Base.MSRP, ev_data$Electric.Range,
     main = "Scatterplot of MSRP vs Electric Range",
     xlab = "Base MSRP ($)",
     ylab = "Electric Range (miles)",
     col = "blue", pch = 19)
```


